### ISSUE TITLE
Unable to add all openebs installation jobs / testcases

### ISSUE THREAD

**Issue by amitbhatt818** [mayadata-io/oep-e2e#542] opened 2020-05-12 06:41 UTC
### What is the issue?

- We have multiple openebs install jobs that needs to be executed into the cluster3 but we are not adding that in the gitlab-ci.yml because of which test case coverage is very low.

### What needs to be done 
- Cluster3 should be setup in the pipeline for Rancher with proper configuration.

**Comment by AmitKumarDas** [comment] 2020-05-15 04:33
This has been unblocked for AWS setup.

**Comment by amitbhatt818** [comment] 2020-05-17 14:08
- Added all the openebs install jobs for AWS.

**Comment by AmitKumarDas** [comment] 2020-05-19 04:28
@harshshekhar15 need to update this issue with addition of install testcases in Rancher setup

**Comment by AmitKumarDas** [comment] 2020-05-20 04:24
There were issues connecting to Cluster 3. Once this issue is resolved, install testcases will be integrated into Rancher setup (i.e. Cluster 3)

**Comment by AmitKumarDas** [comment] 2020-05-21 04:24
These testcases belong to openebs install stage. It needs to run in Cluster 3 __ @amitbhatt818

**Comment by harshshekhar15** [comment] 2020-05-21 22:32
Openebs installation jobs have been added in `openebs-install-tests` branch. Two of the jobs are failing and needs to be fixed. Once the issue is fixed will merge it in `oep-release` branch.
Pipeline details - https://gitlab.mayadata.io/oep/oep-e2e-rancher/pipelines/10788

![image](https://user-images.githubusercontent.com/40303207/82612654-ff835c80-9be0-11ea-8fc4-8ee930e6ea29.png)

**Comment by AmitKumarDas** [comment] 2020-05-27 04:29
Testing is under progress cc @harshshekhar15

**Comment by harshshekhar15** [comment] 2020-05-28 05:04
One of the failing jobs has been fixed. The other job needs to be fixed.

![image](https://user-images.githubusercontent.com/40303207/83100932-b8a8d180-a0ce-11ea-82b7-1b286436ea90.png)

**Comment by prabhatkumarthakur** [comment] 2020-06-01 04:26
@harshshekhar15  Please update the issues with findings.

**Comment by harshshekhar15** [comment] 2020-06-02 17:18
Blocked on - https://github.com/mayadata-io/oep-e2e/issues/632

**Closed** 2020-06-03 14:26 UTC
Labels: blocker, install, slipped, testplan

**Comment by harshshekhar15** [comment] 2020-06-04 21:57
The above issue has been fixed and all the openebs-install testcases have been added to `oep-release` branch of Rancher pipeline. The latest ran successfully with the all the openebs-install testcases.

![Screenshot from 2020-06-05 03-21-10](https://user-images.githubusercontent.com/40303207/83814761-86a1fb80-a6dc-11ea-85e3-6817691398e7.png)
